go.property("goal", msg.url())
go.property("speed", 100)
function init(self)
	self.vel=vmath.vector3()
end

function update(self, dt)
	self.vel=self.direction*self.speed
	local pos = go.get_position()+self.vel*dt
	self.direction=vmath.normalize(go.get_position(self.goal)-go.get_position())
	go.set_position(pos)
	if vmath.length(go.get_position()-go.get_position(self.goal))<10 then
		go.delete()
	end
end